# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0/design_1_system_ila_0.xci
# IP: The module: 'design_1_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/bd_384c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_384c || ORIG_REF_NAME==bd_384c} -quiet] -quiet

# IP: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/bd_384c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0} -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/bd_384c_ila_lib_0_ooc.xdc

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/bd_384c_ooc.xdc

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/design_1_system_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0/design_1_system_ila_0.xci
# IP: The module: 'design_1_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/bd_384c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_384c || ORIG_REF_NAME==bd_384c} -quiet] -quiet

# IP: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/bd_384c_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0} -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/bd_384c_ila_lib_0_ooc.xdc

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/bd_0/bd_384c_ooc.xdc

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HW_Debug/HW_Debug.gen/sources_1/bd/design_1/ip/design_1_system_ila_0/design_1_system_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
