
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_MOTORS_MOTOR_0_AXI_GPIO_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_0_AXI_GPIO_0_BASEADDR,
		XPAR_MOTORS_MOTOR_0_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_MOTORS_MOTOR_0_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_MOTORS_MOTOR_1_AXI_GPIO_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_1_AXI_GPIO_0_BASEADDR,
		XPAR_MOTORS_MOTOR_1_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_MOTORS_MOTOR_1_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_MOTORS_MOTOR_2_AXI_GPIO_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_2_AXI_GPIO_0_BASEADDR,
		XPAR_MOTORS_MOTOR_2_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_MOTORS_MOTOR_2_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_MOTORS_MOTOR_3_AXI_GPIO_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_3_AXI_GPIO_0_BASEADDR,
		XPAR_MOTORS_MOTOR_3_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_MOTORS_MOTOR_3_AXI_GPIO_0_IS_DUAL
	}
};


