set_property SRC_FILE_INFO {cfile:C:/02_PXL/SoC_PXL_2024/VHDL/IMU/IMU.srcs/constrs_1/new/io.xdc rfile:../../../IMU.srcs/constrs_1/new/io.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports iic_rtl_scl_io]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports iic_rtl_sda_io]
