# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/x.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_boolean_sevensegment_0_0/design_1_boolean_sevensegment_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_boolean_sevensegment_0_0 || ORIG_REF_NAME==design_1_boolean_sevensegment_0_0} -quiet] -quiet

# XDC: c:/02_PXL/2023/Digitale_Systemen_PXL_2023/VHDL/Labo/Oef1_1/Labo_week_1_Oef_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
