set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uitgang_0[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_0_IBUF]

set_property PACKAGE_PIN Y18 [get_ports {uitgang_0[6]}]
set_property PACKAGE_PIN Y19 [get_ports {uitgang_0[5]}]
set_property PACKAGE_PIN Y16 [get_ports {uitgang_0[4]}]
set_property PACKAGE_PIN U18 [get_ports {uitgang_0[3]}]
set_property PACKAGE_PIN U19 [get_ports {uitgang_0[2]}]
set_property PACKAGE_PIN W18 [get_ports {uitgang_0[1]}]
set_property PACKAGE_PIN W19 [get_ports {uitgang_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ingang_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ingang_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ingang_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ingang_0[0]}]
set_property PACKAGE_PIN D19 [get_ports {ingang_0[3]}]
set_property PACKAGE_PIN D20 [get_ports {ingang_0[2]}]
set_property PACKAGE_PIN L20 [get_ports {ingang_0[1]}]
set_property PACKAGE_PIN L19 [get_ports {ingang_0[0]}]
