# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
# IP: The module: 'design_1_clk_wiz_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
# IP: The module: 'design_1_clk_wiz_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/VHDL/HC_SR04/HC_SR04.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
