# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SpeedCounter_0_0/design_1_SpeedCounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_SpeedCounter_0_0 || ORIG_REF_NAME==design_1_SpeedCounter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_1/design_1_vio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vio_0_1 || ORIG_REF_NAME==design_1_vio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# XDC: c:/02_PXL/SoC_PXL_2024/hardware_block/Speed_Sensor/Speed_Sensor.gen/sources_1/bd/design_1/design_1_ooc.xdc
