
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[XPAR_XTMRCTR_NUM_INSTANCES] =
{
	{
		XPAR_MOTORS_MOTOR_0_AXI_TIMER_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_0_AXI_TIMER_0_BASEADDR,
		XPAR_MOTORS_MOTOR_0_AXI_TIMER_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_MOTORS_MOTOR_1_AXI_TIMER_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_1_AXI_TIMER_0_BASEADDR,
		XPAR_MOTORS_MOTOR_1_AXI_TIMER_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_MOTORS_MOTOR_2_AXI_TIMER_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_2_AXI_TIMER_0_BASEADDR,
		XPAR_MOTORS_MOTOR_2_AXI_TIMER_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_MOTORS_MOTOR_3_AXI_TIMER_0_DEVICE_ID,
		XPAR_MOTORS_MOTOR_3_AXI_TIMER_0_BASEADDR,
		XPAR_MOTORS_MOTOR_3_AXI_TIMER_0_CLOCK_FREQ_HZ
	}
};


